[pytest]
addopts = [
    "-v"
    # ,"-k smoke"
    # ,"--headed"
    # ,"--slowmo=200"
    , "--browser=chromium"
    , "--browser=webkit"
    , "--browser=firefox"
    # , "--device=\"iPhone 12\""
    , "--video=retain-on-failure"
    , "--screenshot=only-on-failure"
    #, "--output=reports "
]
console_output_style = "count"
log_cli= true
log_cli_level = "INFO"
testpaths = ["tests"]
markers = [
    "smoke"
]
